### ISSUE TITLE
Adjust Models

### ISSUE THREAD

**Issue by NetUnit** [NetUnit/SoftServeItAcademy#159]
Redefine Models according to #156 & #157 issues. Provide more details about errors.

**Comment by AlmoGsh98** [comment]
hey!
I would like to help you with this issue.
this is my first time contributing.
can you explain more about the issue?

**Comment by NetUnit** [comment]
Hi Almog!

Issue #159 corresponds to #156 & #157.  Particularly to add lines that promote logging messages in traceback and write a logging file (purely indicative info).
https://docs.djangoproject.com/en/4.0/topics/logging/
As this project has the educational aim, alongside that, relevant Django exceptions should be raised too.
https://docs.djangoproject.com/en/4.0/ref/exceptions/

U r free to fork a this repository and contribute with pull request of course.
If had issues with that, I'll give U an access but then U need to commit changes to your branch.
Luck!

**Comment by AlmoGsh98** [comment]
Hi, thank for the detailed response!
On the upcoming weekend I will look over everything!

Looking forward to the task!

**Comment by AlmoGsh98** [comment]
> Hi Almog!
> 
> Issue #159 corresponds to #156 & #157. Particularly to add lines that promote logging messages in traceback and write a logging file (purely indicative info). https://docs.djangoproject.com/en/4.0/topics/logging/ As this project has the educational aim, alongside that, relevant Django exceptions should be raised too. https://docs.djangoproject.com/en/4.0/ref/exceptions/
> 
> U r free to fork a this repository and contribute with pull request of course. If had issues with that, I'll give U an access but then U need to commit changes to your branch. Luck!

Hi,
Your mention is for   - SoftServeItAcademy/Dev/bootcamp/lib/python3.8/site-packages/joblib/logger.py File?
